export const GET_DATA_CURRENT = 'GET_DATA_CURRENT';
export const GET_DATA_TODAY = 'GET_DATA_TODAY';
export const GET_DATA_YESTERDAY = 'GET_DATA_YESTERDAY';
export const GET_DATA_WEEK = 'GET_DATA_WEEK';
export const SET_LOADING = 'SET_LOADING';
